In [1]:
import pandas as pd

In [15]:
ls

Annual_Deforesation/
API_AG.LND.IRIG.AG.ZS_DS2_en_excel_v2_10518814.xls
Droughts_ floods_extreme_temperatures/
FAOSTAT_temp_change_data/
Forest_Area/
forest-area-as-share-of-land-area_ourworldindata_ByCountry.csv
forest-area-km_ourworldindata.csv
Forest_Area_Sq_Km/
natural-disasters-by-type.csv
PM25-air-pollution_ourworldindata.csv
Population_density/
SYB60_T25_Carbon Dioxide Emission Estimates.csv
SYB61_T25_Threatened Species.csv
Terrestial_protected_land/
Untitled.ipynb

In [3]:
df = pd.read_csv("forest-area-km_ourworldindata.csv")

In [5]:
df.shape

(6661, 4)

In [6]:
df.isna().sum()

Entity                            0
Code                           1196
Year                              0
Forest area (sq. km) (km² )       0
dtype: int64

In [9]:
df.head(40)

         Entity Code  Year  Forest area (sq. km) (km² )
0   Afghanistan  AFG  1990                      13500.0
1   Afghanistan  AFG  1991                      13500.0
2   Afghanistan  AFG  1992                      13500.0
3   Afghanistan  AFG  1993                      13500.0
4   Afghanistan  AFG  1994                      13500.0
5   Afghanistan  AFG  1995                      13500.0
6   Afghanistan  AFG  1996                      13500.0
7   Afghanistan  AFG  1997                      13500.0
8   Afghanistan  AFG  1998                      13500.0
9   Afghanistan  AFG  1999                      13500.0
10  Afghanistan  AFG  2000                      13500.0
11  Afghanistan  AFG  2001                      13500.0
12  Afghanistan  AFG  2002                      13500.0
13  Afghanistan  AFG  2003                      13500.0
14  Afghanistan  AFG  2004                      13500.0
15  Afghanistan  AFG  2005                      13500.0
16  Afghanistan  AFG  2006                      13500.0
17  Afghanistan  AFG  2007                      13500.0
18  Afghanistan  AFG  2008                      13500.0
19  Afghanistan  AFG  2009                      13500.0
20  Afghanistan  AFG  2010                      13500.0
21  Afghanistan  AFG  2011                      13500.0
22  Afghanistan  AFG  2012                      13500.0
23  Afghanistan  AFG  2013                      13500.0
24  Afghanistan  AFG  2014                      13500.0
25  Afghanistan  AFG  2015                      13500.0
26      Albania  ALB  1990                       7888.0
27      Albania  ALB  1991                       7868.5
28      Albania  ALB  1992                       7849.0
29      Albania  ALB  1993                       7829.5
30      Albania  ALB  1994                       7810.0
31      Albania  ALB  1995                       7790.5
32      Albania  ALB  1996                       7771.0
33      Albania  ALB  1997                       7751.5
34      Albania  ALB  1998                       7732.0
35      Albania  ALB  1999                       7712.5
36      Albania  ALB  2000                       7693.0
37      Albania  ALB  2001                       7719.2
38      Albania  ALB  2002                       7745.4
39      Albania  ALB  2003                       7771.6

In [28]:
df1 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/FAOSTAT_temp_change_data/Environment_Temperature_change_E_All_Data.csv", encoding = "ISO-8859-1")

In [29]:
df1.shape

(9248, 123)

In [35]:
df1.columns

Index(['Area Code', 'Area', 'Months Code', 'Months', 'Element Code', 'Element',
       'Unit', 'Y1961', 'Y1961F', 'Y1962',
       ...
       'Y2014', 'Y2014F', 'Y2015', 'Y2015F', 'Y2016', 'Y2016F', 'Y2017',
       'Y2017F', 'Y2018', 'Y2018F'],
      dtype='object', length=123)

In [31]:
df1.head(100)

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1961F,Y1962,...,Y2014,Y2014F,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F,Y2018,Y2018F
0,2,Afghanistan,7001,January,7271,Temperature change,°C,0.993,Fc,0.137,...,2.422,Fc,2.278,Fc,3.621,Fc,0.279,Fc,2.700,Fc
1,2,Afghanistan,7001,January,6078,Standard Deviation,°C,1.888,Fc,1.888,...,1.888,Fc,1.888,Fc,1.888,Fc,1.888,Fc,1.888,Fc
2,2,Afghanistan,7002,February,7271,Temperature change,°C,-1.542,Fc,2.421,...,-1.617,Fc,3.687,Fc,1.713,Fc,-0.377,Fc,2.652,Fc
3,2,Afghanistan,7002,February,6078,Standard Deviation,°C,2.456,Fc,2.456,...,2.456,Fc,2.456,Fc,2.456,Fc,2.456,Fc,2.456,Fc
4,2,Afghanistan,7003,March,7271,Temperature change,°C,0.536,Fc,1.444,...,0.171,Fc,-0.133,Fc,1.178,Fc,0.100,Fc,4.214,Fc
5,2,Afghanistan,7003,March,6078,Standard Deviation,°C,1.469,Fc,1.469,...,1.469,Fc,1.469,Fc,1.469,Fc,1.469,Fc,1.469,Fc
6,2,Afghanistan,7004,April,7271,Temperature change,°C,-1.697,Fc,0.022,...,1.084,Fc,1.407,Fc,1.401,Fc,2.827,Fc,2.782,Fc
7,2,Afghanistan,7004,April,6078,Standard Deviation,°C,1.335,Fc,1.335,...,1.335,Fc,1.335,Fc,1.335,Fc,1.335,Fc,1.335,Fc
8,2,Afghanistan,7005,May,7271,Temperature change,°C,1.483,Fc,-0.052,...,1.306,Fc,1.447,Fc,2.086,Fc,3.184,Fc,1.271,Fc
9,2,Afghanistan,7005,May,6078,Standard Deviation,°C,1.223,Fc,1.223,...,1.223,Fc,1.223,Fc,1.223,Fc,1.223,Fc,1.223,Fc
10,2,Afghanistan,7006,June,7271,Temperature change,°C,-0.176,Fc,-1.232,...,1.931,Fc,1.627,Fc,2.679,Fc,3.064,Fc,2.455,Fc
11,2,Afghanistan,7006,June,6078,Standard Deviation,°C,0.912,Fc,0.912,...,0.912,Fc,0.912,Fc,0.912,Fc,0.912,Fc,0.912,Fc
12,2,Afghanistan,7007,July,7271,Temperature change,°C,0.803,Fc,0.171,...,2.007,Fc,1.539,Fc,2.345,Fc,1.560,Fc,2.402,Fc
13,2,Afghanistan,7007,July,6078,Standard Deviation,°C,0.629,Fc,0.629,...,0.629,Fc,0.629,Fc,0.629,Fc,0.629,Fc,0.629,Fc
14,2,Afghanistan,7008,August,7271,Temperature change,°C,0.337,Fc,-0.321,...,1.016,Fc,1.049,Fc,1.251,Fc,0.971,Fc,1.822,Fc
15,2,Afghanistan,7008,August,6078,Standard Deviation,°C,0.762,Fc,0.762,...,0.762,Fc,0.762,Fc,0.762,Fc,0.762,Fc,0.762,Fc
16,2,Afghanistan,7009,September,7271,Temperature change,°C,1.414,Fc,-1.870,...,3.296,Fc,0.050,Fc,3.148,Fc,1.246,Fc,1.850,Fc
17,2,Afghanistan,7009,September,6078,Standard Deviation,°C,0.835,Fc,0.835,...,0.835,Fc,0.835,Fc,0.835,Fc,0.835,Fc,0.835,Fc
18,2,Afghanistan,7010,October,7271,Temperature change,°C,-0.983,Fc,-1.092,...,2.286,Fc,2.417,Fc,1.449,Fc,2.993,Fc,0.593,Fc
19,2,Afghanistan,7010,October,6078,Standard Deviation,°C,1.317,Fc,1.317,...,1.317,Fc,1.317,Fc,1.317,Fc,1.317,Fc,1.317,Fc
20,2,Afghanistan,7011,November,7271,Temperature change,°C,-0.793,Fc,-1.896,...,0.941,Fc,1.156,Fc,0.434,Fc,2.141,Fc,1.283,Fc
21,2,Afghanistan,7011,November,6078,Standard Deviation,°C,1.338,Fc,1.338,...,1.338,Fc,1.338,Fc,1.338,Fc,1.338,Fc,1.338,Fc
22,2,Afghanistan,7012,December,7271,Temperature change,°C,0.423,Fc,-1.013,...,0.440,Fc,0.492,Fc,2.597,Fc,0.321,Fc,1.537,Fc
23,2,Afghanistan,7012,December,6078,Standard Deviation,°C,1.453,Fc,1.453,...,1.453,Fc,1.453,Fc,1.453,Fc,1.453,Fc,1.453,Fc
24,2,Afghanistan,7016,DecJanFeb,7271,Temperature change,°C,-0.543,Fc,0.994,...,0.518,Fc,2.135,Fc,1.942,Fc,0.833,Fc,1.891,Fc
25,2,Afghanistan,7016,DecJanFeb,6078,Standard Deviation,°C,1.263,Fc,1.263,...,1.263,Fc,1.263,Fc,1.263,Fc,1.263,Fc,1.263,Fc
26,2,Afghanistan,7017,MarAprMay,7271,Temperature change,°C,0.107,Fc,0.471,...,0.854,Fc,0.907,Fc,1.555,Fc,2.037,Fc,2.756,Fc
27,2,Afghanistan,7017,MarAprMay,6078,Standard Deviation,°C,0.896,Fc,0.896,...,0.896,Fc,0.896,Fc,0.896,Fc,0.896,Fc,0.896,Fc
28,2,Afghanistan,7018,JunJulAug,7271,Temperature change,°C,0.321,Fc,-0.461,...,1.651,Fc,1.405,Fc,2.092,Fc,1.865,Fc,2.226,Fc
29,2,Afghanistan,7018,JunJulAug,6078,Standard Deviation,°C,0.556,Fc,0.556,...,0.556,Fc,0.556,Fc,0.556,Fc,0.556,Fc,0.556,Fc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,4,Algeria,7002,February,7271,Temperature change,°C,0.571,Fc,-1.570,...,0.916,Fc,-0.809,Fc,1.693,Fc,2.128,Fc,-0.669,Fc
71,4,Algeria,7002,February,6078,Standard Deviation,°C,1.290,Fc,1.290,...,1.290,Fc,1.290,Fc,1.290,Fc,1.290,Fc,1.290,Fc
72,4,Algeria,7003,March,7271,Temperature change,°C,-0.603,Fc,-0.331,...,0.149,Fc,-0.326,Fc,-0.050,Fc,2.096,Fc,1.751,Fc
73,4,Algeria,7003,March,6078,Standard Deviation,°C,1.122,Fc,1.122,...,1.122,Fc,1.122,Fc,1.122,Fc,1.122,Fc,1.122,Fc
74,4,Algeria,7004,April,7271,Temperature change,°C,2.564,Fc,0.723,...,2.919,Fc,3.329,Fc,3.848,Fc,2.266,Fc,2.174,Fc
75,4,Algeria,7004,April,6078,Standard Deviation,°C,1.071,Fc,1.071,...,1.071,Fc,1.071,Fc,1.071,Fc,1.071,Fc,1.071,Fc
76,4,Algeria,7005,May,7271,Temperature change,°C,1.946,Fc,0.885,...,2.371,Fc,3.195,Fc,2.627,Fc,4.238,Fc,1.095,Fc
77,4,Algeria,7005,May,6078,Standard Deviation,°C,1.035,Fc,1.035,...,1.035,Fc,1.035,Fc,1.035,Fc,1.035,Fc,1.035,Fc
78,4,Algeria,7006,June,7271,Temperature change,°C,0.066,Fc,-0.399,...,0.764,Fc,1.054,Fc,2.008,Fc,1.702,Fc,1.298,Fc
79,4,Algeria,7006,June,6078,Standard Deviation,°C,0.708,Fc,0.708,...,0.708,Fc,0.708,Fc,0.708,Fc,0.708,Fc,0.708,Fc
80,4,Algeria,7007,July,7271,Temperature change,°C,0.164,Fc,0.525,...,2.275,Fc,1.064,Fc,1.692,Fc,1.880,Fc,3.484,Fc
81,4,Algeria,7007,July,6078,Standard Deviation,°C,0.615,Fc,0.615,...,0.615,Fc,0.615,Fc,0.615,Fc,0.615,Fc,0.615,Fc
82,4,Algeria,7008,August,7271,Temperature change,°C,-0.275,Fc,-0.117,...,2.191,Fc,1.822,Fc,0.865,Fc,1.708,Fc,0.226,Fc
83,4,Algeria,7008,August,6078,Standard Deviation,°C,0.547,Fc,0.547,...,0.547,Fc,0.547,Fc,0.547,Fc,0.547,Fc,0.547,Fc
84,4,Algeria,7009,September,7271,Temperature change,°C,0.262,Fc,0.882,...,2.885,Fc,1.464,Fc,1.801,Fc,1.451,Fc,1.415,Fc
85,4,Algeria,7009,September,6078,Standard Deviation,°C,0.487,Fc,0.487,...,0.487,Fc,0.487,Fc,0.487,Fc,0.487,Fc,0.487,Fc
86,4,Algeria,7010,October,7271,Temperature change,°C,0.262,Fc,1.049,...,2.379,Fc,2.606,Fc,3.207,Fc,0.780,Fc,1.077,Fc
87,4,Algeria,7010,October,6078,Standard Deviation,°C,0.832,Fc,0.832,...,0.832,Fc,0.832,Fc,0.832,Fc,0.832,Fc,0.832,Fc
88,4,Algeria,7011,November,7271,Temperature change,°C,1.744,Fc,-0.731,...,2.014,Fc,1.117,Fc,1.222,Fc,0.166,Fc,1.149,Fc
89,4,Algeria,7011,November,6078,Standard Deviation,°C,1.063,Fc,1.063,...,1.063,Fc,1.063,Fc,1.063,Fc,1.063,Fc,1.063,Fc
90,4,Algeria,7012,December,7271,Temperature change,°C,0.862,Fc,-0.266,...,-0.031,Fc,1.085,Fc,1.569,Fc,-0.092,Fc,1.246,Fc
91,4,Algeria,7012,December,6078,Standard Deviation,°C,1.141,Fc,1.141,...,1.141,Fc,1.141,Fc,1.141,Fc,1.141,Fc,1.141,Fc
92,4,Algeria,7016,DecJanFeb,7271,Temperature change,°C,-0.530,Fc,0.052,...,0.806,Fc,-0.417,Fc,1.706,Fc,0.649,Fc,0.230,Fc
93,4,Algeria,7016,DecJanFeb,6078,Standard Deviation,°C,0.850,Fc,0.850,...,0.850,Fc,0.850,Fc,0.850,Fc,0.850,Fc,0.850,Fc
94,4,Algeria,7017,MarAprMay,7271,Temperature change,°C,1.302,Fc,0.426,...,1.813,Fc,2.066,Fc,2.142,Fc,2.867,Fc,1.673,Fc
95,4,Algeria,7017,MarAprMay,6078,Standard Deviation,°C,0.579,Fc,0.579,...,0.579,Fc,0.579,Fc,0.579,Fc,0.579,Fc,0.579,Fc
96,4,Algeria,7018,JunJulAug,7271,Temperature change,°C,-0.015,Fc,0.003,...,1.743,Fc,1.313,Fc,1.522,Fc,1.763,Fc,1.669,Fc
97,4,Algeria,7018,JunJulAug,6078,Standard Deviation,°C,0.421,Fc,0.421,...,0.421,Fc,0.421,Fc,0.421,Fc,0.421,Fc,0.421,Fc
98,4,Algeria,7019,SepOctNov,7271,Temperature change,°C,0.756,Fc,0.400,...,2.426,Fc,1.729,Fc,2.077,Fc,0.799,Fc,1.214,Fc
99,4,Algeria,7019,SepOctNov,6078,Standard Deviation,°C,0.567,Fc,0.567,...,0.567,Fc,0.567,Fc,0.567,Fc,0.567,Fc,0.567,Fc

In [32]:
df2 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/FAOSTAT_temp_change_data/Environment_Temperature_change_E_All_Data_NOFLAG.csv", encoding = "ISO-8859-1")

In [33]:
df2.head()

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1962,Y1963,...,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018
0,2,Afghanistan,7001,January,7271,Temperature change,°C,0.993,0.137,2.441,...,1.764,3.677,1.096,-0.304,2.136,2.422,2.278,3.621,0.279,2.700
1,2,Afghanistan,7001,January,6078,Standard Deviation,°C,1.888,1.888,1.888,...,1.888,1.888,1.888,1.888,1.888,1.888,1.888,1.888,1.888,1.888
2,2,Afghanistan,7002,February,7271,Temperature change,°C,-1.542,2.421,3.849,...,3.025,0.857,1.112,-2.161,0.348,-1.617,3.687,1.713,-0.377,2.652
3,2,Afghanistan,7002,February,6078,Standard Deviation,°C,2.456,2.456,2.456,...,2.456,2.456,2.456,2.456,2.456,2.456,2.456,2.456,2.456,2.456
4,2,Afghanistan,7003,March,7271,Temperature change,°C,0.536,1.444,0.327,...,2.543,4.204,1.837,0.464,-1.072,0.171,-0.133,1.178,0.100,4.214

In [34]:
df2.shape

(9248, 65)

In [36]:
df2.columns

Index(['Area Code', 'Area', 'Months Code', 'Months', 'Element Code', 'Element',
       'Unit', 'Y1961', 'Y1962', 'Y1963', 'Y1964', 'Y1965', 'Y1966', 'Y1967',
       'Y1968', 'Y1969', 'Y1970', 'Y1971', 'Y1972', 'Y1973', 'Y1974', 'Y1975',
       'Y1976', 'Y1977', 'Y1978', 'Y1979', 'Y1980', 'Y1981', 'Y1982', 'Y1983',
       'Y1984', 'Y1985', 'Y1986', 'Y1987', 'Y1988', 'Y1989', 'Y1990', 'Y1991',
       'Y1992', 'Y1993', 'Y1994', 'Y1995', 'Y1996', 'Y1997', 'Y1998', 'Y1999',
       'Y2000', 'Y2001', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007',
       'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015',
       'Y2016', 'Y2017', 'Y2018'],
      dtype='object')

In [51]:
df3 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/SYB60_T25_Carbon Dioxide Emission Estimates.csv", encoding = "ISO-8859-1")

In [52]:
df3.head(100)

,T25,CO2 emission estimates,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Region/Country/Area,NaN,Year,Series,Value,Footnotes,Source
1,1,"Total, all countries or areas",1975,Emissions (thousand metric tons of carbon diox...,"16,853,532",NaN,Carbon Dioxide Information Analysis Center (CD...
2,1,"Total, all countries or areas",1985,Emissions (thousand metric tons of carbon diox...,"19,864,139",NaN,Carbon Dioxide Information Analysis Center (CD...
3,1,"Total, all countries or areas",1995,Emissions (thousand metric tons of carbon diox...,"23,120,435",NaN,Carbon Dioxide Information Analysis Center (CD...
4,1,"Total, all countries or areas",2005,Emissions (thousand metric tons of carbon diox...,"29,490,014",NaN,Carbon Dioxide Information Analysis Center (CD...
5,1,"Total, all countries or areas",2010,Emissions (thousand metric tons of carbon diox...,"33,472,376",NaN,Carbon Dioxide Information Analysis Center (CD...
6,1,"Total, all countries or areas",2012,Emissions (thousand metric tons of carbon diox...,"35,470,891",NaN,Carbon Dioxide Information Analysis Center (CD...
7,1,"Total, all countries or areas",2013,Emissions (thousand metric tons of carbon diox...,"35,837,591",NaN,Carbon Dioxide Information Analysis Center (CD...
8,1,"Total, all countries or areas",2014,Emissions (thousand metric tons of carbon diox...,"36,138,285",NaN,Carbon Dioxide Information Analysis Center (CD...
9,1,"Total, all countries or areas",1975,Emissions per capita (metric tons of carbon di...,4.1,NaN,Carbon Dioxide Information Analysis Center (CD...
10,1,"Total, all countries or areas",1985,Emissions per capita (metric tons of carbon di...,4.1,NaN,Carbon Dioxide Information Analysis Center (CD...
11,1,"Total, all countries or areas",1995,Emissions per capita (metric tons of carbon di...,4.0,NaN,Carbon Dioxide Information Analysis Center (CD...
12,1,"Total, all countries or areas",2005,Emissions per capita (metric tons of carbon di...,4.5,NaN,Carbon Dioxide Information Analysis Center (CD...
13,1,"Total, all countries or areas",2010,Emissions per capita (metric tons of carbon di...,4.8,NaN,Carbon Dioxide Information Analysis Center (CD...
14,1,"Total, all countries or areas",2012,Emissions per capita (metric tons of carbon di...,5.0,NaN,Carbon Dioxide Information Analysis Center (CD...
15,1,"Total, all countries or areas",2013,Emissions per capita (metric tons of carbon di...,5.0,NaN,Carbon Dioxide Information Analysis Center (CD...
16,1,"Total, all countries or areas",2014,Emissions per capita (metric tons of carbon di...,5.0,NaN,Carbon Dioxide Information Analysis Center (CD...
17,4,Afghanistan,1975,Emissions (thousand metric tons of carbon diox...,"2,127",NaN,Carbon Dioxide Information Analysis Center (CD...
18,4,Afghanistan,1985,Emissions (thousand metric tons of carbon diox...,"3,509",NaN,Carbon Dioxide Information Analysis Center (CD...
19,4,Afghanistan,1995,Emissions (thousand metric tons of carbon diox...,"1,243",NaN,Carbon Dioxide Information Analysis Center (CD...
20,4,Afghanistan,2005,Emissions (thousand metric tons of carbon diox...,"1,327",NaN,Carbon Dioxide Information Analysis Center (CD...
21,4,Afghanistan,2010,Emissions (thousand metric tons of carbon diox...,"8,463",NaN,Carbon Dioxide Information Analysis Center (CD...
22,4,Afghanistan,2012,Emissions (thousand metric tons of carbon diox...,"10,755",NaN,Carbon Dioxide Information Analysis Center (CD...
23,4,Afghanistan,2013,Emissions (thousand metric tons of carbon diox...,"10,015",NaN,Carbon Dioxide Information Analysis Center (CD...
24,4,Afghanistan,2014,Emissions (thousand metric tons of carbon diox...,"9,809",NaN,Carbon Dioxide Information Analysis Center (CD...
25,4,Afghanistan,1975,Emissions per capita (metric tons of carbon di...,0.1,NaN,Carbon Dioxide Information Analysis Center (CD...
26,4,Afghanistan,1985,Emissions per capita (metric tons of carbon di...,0.3,NaN,Carbon Dioxide Information Analysis Center (CD...
27,4,Afghanistan,1995,Emissions per capita (metric tons of carbon di...,0.1,NaN,Carbon Dioxide Information Analysis Center (CD...
28,4,Afghanistan,2005,Emissions per capita (metric tons of carbon di...,0.0,NaN,Carbon Dioxide Information Analysis Center (CD...
29,4,Afghanistan,2010,Emissions per capita (metric tons of carbon di...,0.3,NaN,Carbon Dioxide Information Analysis Center (CD...
...,...,...,...,...,...,...,...
70,20,Andorra,2014,Emissions (thousand metric tons of carbon diox...,462,NaN,Carbon Dioxide Information Analysis Center (CD...
71,20,Andorra,1995,Emissions per capita (metric tons of carbon di...,6.6,NaN,Carbon Dioxide Information Analysis Center (CD...
72,20,Andorra,2005,Emissions per capita (metric tons of carbon di...,7.4,NaN,Carbon Dioxide Information Analysis Center (CD...
73,20,Andorra,2010,Emissions per capita (metric tons of carbon di...,6.2,NaN,Carbon Dioxide Information Analysis Center (CD...
74,20,Andorra,2012,Emissions per capita (metric tons of carbon di...,6.2,NaN,Carbon Dioxide Information Analysis Center (CD...
75,20,Andorra,2013,Emissions per capita (metric tons of carbon di...,6.3,NaN,Carbon Dioxide Information Analysis Center (CD...
76,20,Andorra,2014,Emissions per capita (metric tons of carbon di...,6.4,NaN,Carbon Dioxide Information Analysis Center (CD...
77,24,Angola,1975,Emissions (thousand metric tons of carbon diox...,"4,415",NaN,Carbon Dioxide Information Analysis Center (CD...
78,24,Angola,1985,Emissions (thousand metric tons of carbon diox...,"4,701",NaN,Carbon Dioxide Information Analysis Center (CD...
79,24,Angola,1995,Emissions (thousand metric tons of carbon diox...,"10,975",NaN,Carbon Dioxide Information Analysis Center (CD...
80,24,Angola,2005,Emissions (thousand metric tons of carbon diox...,"19,156",NaN,Carbon Dioxide Information Analysis Center (CD...
81,24,Angola,2010,Emissions (thousand metric tons of carbon diox...,"29,057",NaN,Carbon Dioxide Information Analysis Center (CD...
82,24,Angola,2012,Emissions (thousand metric tons of carbon diox...,"33,399",NaN,Carbon Dioxide Information Analysis Center (CD...
83,24,Angola,2013,Emissions (thousand metric tons of carbon diox...,"32,618",NaN,Carbon Dioxide Information Analysis Center (CD...
84,24,Angola,2014,Emissions (thousand metric tons of carbon diox...,"34,763",NaN,Carbon Dioxide Information Analysis Center (CD...
85,24,Angola,1975,Emissions per capita (metric tons of carbon di...,0.7,NaN,Carbon Dioxide Information Analysis Center (CD...
86,24,Angola,1985,Emissions per capita (metric tons of carbon di...,0.5,NaN,Carbon Dioxide Information Analysis Center (CD...
87,24,Angola,1995,Emissions per capita (metric tons of carbon di...,0.9,NaN,Carbon Dioxide Information Analysis Center (CD...
88,24,Angola,2005,Emissions per capita (metric tons of carbon di...,1.2,NaN,Carbon Dioxide Information Analysis Center (CD...
89,24,Angola,2010,Emissions per capita (metric tons of carbon di...,1.4,NaN,Carbon Dioxide Information Analysis Center (CD...
90,24,Angola,2012,Emissions per capita (metric tons of carbon di...,1.5,NaN,Carbon Dioxide Information Analysis Center (CD...
91,24,Angola,2013,Emissions per capita (metric tons of carbon di...,1.4,NaN,Carbon Dioxide Information Analysis Center (CD...
92,24,Angola,2014,Emissions per capita (metric tons of carbon di...,1.4,NaN,Carbon Dioxide Information Analysis Center (CD...
93,660,Anguilla,1995,Emissions (thousand metric tons of carbon diox...,66,NaN,Carbon Dioxide Information Analysis Center (CD...
94,660,Anguilla,2005,Emissions (thousand metric tons of carbon diox...,128,NaN,Carbon Dioxide Information Analysis Center (CD...
95,660,Anguilla,2010,Emissions (thousand metric tons of carbon diox...,150,NaN,Carbon Dioxide Information Analysis Center (CD...
96,660,Anguilla,2012,Emissions (thousand metric tons of carbon diox...,143,NaN,Carbon Dioxide Information Analysis Center (CD...
97,660,Anguilla,2013,Emissions (thousand metric tons of carbon diox...,136,NaN,Carbon Dioxide Information Analysis Center (CD...
98,660,Anguilla,2014,Emissions (thousand metric tons of carbon diox...,143,NaN,Carbon Dioxide Information Analysis Center (CD...
99,660,Anguilla,1995,Emissions per capita (metric tons of carbon di...,6.9,NaN,Carbon Dioxide Information Analysis Center (CD...

In [53]:
df4 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/PM25-air-pollution_ourworldindata.csv", encoding = "ISO-8859-1")

In [54]:
df4.head(100)

,Entity,Code,Year,"PM2.5 air pollution, mean annual exposure (micrograms per cubic meter) (micrograms per cubic meter)"
0,Afghanistan,AFG,1990,60.936690
1,Afghanistan,AFG,1995,56.136628
2,Afghanistan,AFG,2000,56.092028
3,Afghanistan,AFG,2005,43.234032
4,Afghanistan,AFG,2010,46.536809
5,Afghanistan,AFG,2011,50.483960
6,Afghanistan,AFG,2012,50.653945
7,Afghanistan,AFG,2013,50.968831
8,Afghanistan,AFG,2014,49.036091
9,Afghanistan,AFG,2015,62.080234
10,Afghanistan,AFG,2016,62.854857
11,Albania,ALB,1990,17.796006
12,Albania,ALB,1995,15.072604
13,Albania,ALB,2000,14.320845
14,Albania,ALB,2005,12.155814
15,Albania,ALB,2010,15.335690
16,Albania,ALB,2011,14.646135
17,Albania,ALB,2012,14.562992
18,Albania,ALB,2013,15.635917
19,Albania,ALB,2014,16.748862
20,Albania,ALB,2015,14.736548
21,Albania,ALB,2016,14.634008
22,Algeria,DZA,1990,34.023754
23,Algeria,DZA,1995,33.398080
24,Algeria,DZA,2000,32.211591
25,Algeria,DZA,2005,28.434431
26,Algeria,DZA,2010,26.709349
27,Algeria,DZA,2011,27.497075
28,Algeria,DZA,2012,28.209439
29,Algeria,DZA,2013,31.009854
...,...,...,...,...
70,Antigua and Barbuda,ATG,2010,13.374218
71,Antigua and Barbuda,ATG,2011,13.613442
72,Antigua and Barbuda,ATG,2012,13.711044
73,Antigua and Barbuda,ATG,2013,14.014765
74,Antigua and Barbuda,ATG,2014,13.768418
75,Antigua and Barbuda,ATG,2015,15.517696
76,Antigua and Barbuda,ATG,2016,15.685943
77,Arab World,NaN,1990,53.192325
78,Arab World,NaN,1995,51.824856
79,Arab World,NaN,2000,52.903983
80,Arab World,NaN,2005,52.763005
81,Arab World,NaN,2010,63.791725
82,Arab World,NaN,2011,63.148567
83,Arab World,NaN,2012,63.801393
84,Arab World,NaN,2013,63.391541
85,Arab World,NaN,2014,62.994614
86,Arab World,NaN,2015,81.936630
87,Arab World,NaN,2016,83.151463
88,Argentina,ARG,1990,15.912569
89,Argentina,ARG,1995,16.058822
90,Argentina,ARG,2000,15.603643
91,Argentina,ARG,2005,14.820324
92,Argentina,ARG,2010,14.224179
93,Argentina,ARG,2011,14.061859
94,Argentina,ARG,2012,14.075854
95,Argentina,ARG,2013,13.577209
96,Argentina,ARG,2014,13.643647
97,Argentina,ARG,2015,14.117203
98,Argentina,ARG,2016,14.148167
99,Armenia,ARM,1990,20.732188

In [55]:
df5 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/natural-disasters-by-type.csv", encoding = "ISO-8859-1")

In [56]:
df5.head(100)

,Entity,Code,Year,Number of reported natural disasters (reported disasters)
0,All natural disasters,NaN,1900,5
1,All natural disasters,NaN,1901,2
2,All natural disasters,NaN,1902,9
3,All natural disasters,NaN,1903,8
4,All natural disasters,NaN,1904,2
5,All natural disasters,NaN,1905,4
6,All natural disasters,NaN,1906,17
7,All natural disasters,NaN,1907,5
8,All natural disasters,NaN,1908,4
9,All natural disasters,NaN,1909,11
10,All natural disasters,NaN,1910,15
11,All natural disasters,NaN,1911,5
12,All natural disasters,NaN,1912,7
13,All natural disasters,NaN,1913,5
14,All natural disasters,NaN,1914,6
15,All natural disasters,NaN,1915,7
16,All natural disasters,NaN,1916,2
17,All natural disasters,NaN,1917,6
18,All natural disasters,NaN,1918,7
19,All natural disasters,NaN,1919,4
20,All natural disasters,NaN,1920,7
21,All natural disasters,NaN,1921,2
22,All natural disasters,NaN,1922,6
23,All natural disasters,NaN,1923,12
24,All natural disasters,NaN,1924,4
25,All natural disasters,NaN,1925,6
26,All natural disasters,NaN,1926,15
27,All natural disasters,NaN,1927,12
28,All natural disasters,NaN,1928,17
29,All natural disasters,NaN,1929,6
...,...,...,...,...
70,All natural disasters,NaN,1970,77
71,All natural disasters,NaN,1971,61
72,All natural disasters,NaN,1972,63
73,All natural disasters,NaN,1973,60
74,All natural disasters,NaN,1974,68
75,All natural disasters,NaN,1975,63
76,All natural disasters,NaN,1976,91
77,All natural disasters,NaN,1977,121
78,All natural disasters,NaN,1978,115
79,All natural disasters,NaN,1979,120
80,All natural disasters,NaN,1980,133
81,All natural disasters,NaN,1981,138
82,All natural disasters,NaN,1982,153
83,All natural disasters,NaN,1983,205
84,All natural disasters,NaN,1984,146
85,All natural disasters,NaN,1985,165
86,All natural disasters,NaN,1986,150
87,All natural disasters,NaN,1987,191
88,All natural disasters,NaN,1988,200
89,All natural disasters,NaN,1989,172
90,All natural disasters,NaN,1990,278
91,All natural disasters,NaN,1991,228
92,All natural disasters,NaN,1992,204
93,All natural disasters,NaN,1993,260
94,All natural disasters,NaN,1994,246
95,All natural disasters,NaN,1995,248
96,All natural disasters,NaN,1996,227
97,All natural disasters,NaN,1997,261
98,All natural disasters,NaN,1998,288
99,All natural disasters,NaN,1999,337

In [58]:
df6 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/forest-area-as-share-of-land-area_ourworldindata_ByCountry.csv", encoding = "ISO-8859-1")

In [59]:
df6.head(100)

,Entity,Code,Year,15.1.1 - Forest area as a proportion of total land area - AG_LND_FRST - Percent (%)
0,Afghanistan,AFG,1990,2.07
1,Afghanistan,AFG,2000,2.07
2,Afghanistan,AFG,2005,2.07
3,Afghanistan,AFG,2010,2.07
4,Afghanistan,AFG,2015,2.07
5,Albania,ALB,1990,28.79
6,Albania,ALB,2000,28.08
7,Albania,ALB,2005,28.55
8,Albania,ALB,2010,28.33
9,Albania,ALB,2015,28.16
10,Algeria,DZA,1990,0.70
11,Algeria,DZA,2000,0.66
12,Algeria,DZA,2005,0.64
13,Algeria,DZA,2010,0.81
14,Algeria,DZA,2015,0.82
15,American Samoa,ASM,1990,91.94
16,American Samoa,ASM,2000,90.25
17,American Samoa,ASM,2005,89.41
18,American Samoa,ASM,2010,88.56
19,American Samoa,ASM,2015,87.72
20,Andorra,AND,1990,34.04
21,Andorra,AND,2000,34.04
22,Andorra,AND,2005,34.04
23,Andorra,AND,2010,34.04
24,Andorra,AND,2015,34.04
25,Angola,AGO,1990,48.91
26,Angola,AGO,2000,47.91
27,Angola,AGO,2005,47.41
28,Angola,AGO,2010,46.91
29,Angola,AGO,2015,46.41
...,...,...,...,...
70,Azerbaijan,AZE,1990,10.31
71,Azerbaijan,AZE,2000,10.55
72,Azerbaijan,AZE,2005,10.61
73,Azerbaijan,AZE,2010,12.20
74,Azerbaijan,AZE,2015,13.78
75,Bahamas,BHS,1990,51.45
76,Bahamas,BHS,2000,51.45
77,Bahamas,BHS,2005,51.45
78,Bahamas,BHS,2010,51.45
79,Bahamas,BHS,2015,51.45
80,Bahrain,BHR,1990,0.28
81,Bahrain,BHR,2000,0.49
82,Bahrain,BHR,2005,0.59
83,Bahrain,BHR,2010,0.69
84,Bahrain,BHR,2015,0.79
85,Bangladesh,BGD,1990,11.48
86,Bangladesh,BGD,2000,11.28
87,Bangladesh,BGD,2005,11.18
88,Bangladesh,BGD,2010,11.08
89,Bangladesh,BGD,2015,10.98
90,Barbados,BRB,1990,14.65
91,Barbados,BRB,2000,14.65
92,Barbados,BRB,2005,14.65
93,Barbados,BRB,2010,14.65
94,Barbados,BRB,2015,14.65
95,Belarus,BLR,1990,37.50
96,Belarus,BLR,2000,39.87
97,Belarus,BLR,2005,40.66
98,Belarus,BLR,2010,41.13
99,Belarus,BLR,2015,41.61

In [60]:
df7 = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Deforestaion_Project/land-use-over-the-long-term.csv", encoding = "ISO-8859-1")

In [66]:
df7.head(200)

,Entity,Code,Year,Built-up Area (hectares),Grazing (hectares),Cropland (hectares)
0,Africa,NaN,-10000,1,0.000000e+00,0.000000e+00
1,Africa,NaN,-9000,2,0.000000e+00,0.000000e+00
2,Africa,NaN,-8000,4,0.000000e+00,0.000000e+00
3,Africa,NaN,-7000,7,0.000000e+00,7.711773e+03
4,Africa,NaN,-6000,14,0.000000e+00,1.649184e+05
5,Africa,NaN,-5000,30,5.845343e+06,8.391652e+05
6,Africa,NaN,-4000,107,1.120671e+07,4.396548e+06
7,Africa,NaN,-3000,361,1.939875e+07,6.526043e+06
8,Africa,NaN,-2000,621,3.322474e+07,6.605707e+06
9,Africa,NaN,-1000,977,5.842015e+07,8.585604e+06
10,Africa,NaN,0,2033,9.043100e+07,1.174674e+07
11,Africa,NaN,100,2409,9.646864e+07,1.246970e+07
12,Africa,NaN,200,2820,1.022557e+08,1.328618e+07
13,Africa,NaN,300,2865,1.080437e+08,1.361025e+07
14,Africa,NaN,400,2893,1.148153e+08,1.412019e+07
15,Africa,NaN,500,2808,1.232553e+08,1.485520e+07
16,Africa,NaN,600,2704,1.331910e+08,1.589117e+07
17,Africa,NaN,700,3167,1.450418e+08,1.773792e+07
18,Africa,NaN,800,3860,1.594416e+08,2.018409e+07
19,Africa,NaN,900,4714,1.711993e+08,2.234092e+07
20,Africa,NaN,1000,5851,1.824782e+08,2.450401e+07
21,Africa,NaN,1100,6491,1.927777e+08,2.561932e+07
22,Africa,NaN,1200,9174,2.026254e+08,2.703986e+07
23,Africa,NaN,1300,18662,2.183861e+08,2.979515e+07
24,Africa,NaN,1400,21258,2.336008e+08,3.189268e+07
25,Africa,NaN,1500,24884,2.418994e+08,3.387758e+07
26,Africa,NaN,1600,32913,2.636678e+08,3.965025e+07
27,Africa,NaN,1700,38019,3.146296e+08,4.362169e+07
28,Africa,NaN,1710,41463,3.079707e+08,4.351362e+07
29,Africa,NaN,1720,45667,3.129197e+08,4.385143e+07
...,...,...,...,...,...,...
170,Canada,CAN,1200,37,0.000000e+00,0.000000e+00
171,Canada,CAN,1300,126,0.000000e+00,0.000000e+00
172,Canada,CAN,1400,140,0.000000e+00,0.000000e+00
173,Canada,CAN,1500,182,0.000000e+00,9.999996e+02
174,Canada,CAN,1600,211,0.000000e+00,9.999993e+02
175,Canada,CAN,1700,211,0.000000e+00,2.250320e+04
176,Canada,CAN,1710,255,0.000000e+00,2.955196e+04
177,Canada,CAN,1720,323,0.000000e+00,3.942053e+04
178,Canada,CAN,1730,408,0.000000e+00,5.166665e+04
179,Canada,CAN,1740,513,0.000000e+00,6.902109e+04
180,Canada,CAN,1750,643,0.000000e+00,9.144315e+04
181,Canada,CAN,1760,807,0.000000e+00,1.221933e+05
182,Canada,CAN,1770,1015,4.091688e+04,1.639277e+05
183,Canada,CAN,1780,1283,6.137534e+04,2.202714e+05
184,Canada,CAN,1790,1632,9.206276e+04,2.979211e+05
185,Canada,CAN,1800,2095,1.380950e+05,4.343760e+05
186,Canada,CAN,1810,2716,2.255026e+05,5.938608e+05
187,Canada,CAN,1820,3594,3.382596e+05,8.156822e+05
188,Canada,CAN,1830,4818,5.073728e+05,1.125665e+06
189,Canada,CAN,1840,6553,7.610803e+05,1.563047e+06
190,Canada,CAN,1850,9045,1.141580e+06,2.177984e+06
191,Canada,CAN,1860,15015,1.712395e+06,3.540646e+06
192,Canada,CAN,1870,20858,2.574614e+06,4.908126e+06
193,Canada,CAN,1880,26608,3.137105e+06,6.088163e+06
194,Canada,CAN,1890,34026,4.012424e+06,7.635577e+06
195,Canada,CAN,1900,39728,4.046474e+06,8.389981e+06
196,Canada,CAN,1910,53572,5.858334e+06,1.448681e+07
197,Canada,CAN,1920,67121,9.629938e+06,2.024188e+07
198,Canada,CAN,1930,81929,1.229064e+07,2.359991e+07
199,Canada,CAN,1940,94366,1.573900e+07,3.317743e+07